/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#pragma mark Named Structures

struct CGPoint {
    float x;
    float y;
};

struct CGRect {
    struct CGPoint _field1;
    struct CGSize _field2;
};

struct CGSize {
    float width;
    float height;
};

struct PBOpenGLContextPriv {
    struct _opaque_pthread_mutex_t _field1;
    struct _opaque_pthread_mutex_t _field2;
    id _field3;
    id _field4;
    id _field5;
    unsigned int _field6;
    unsigned int _field7;
    unsigned int _field8;
    unsigned int _field9;
    unsigned int _field10;
    unsigned int _field11;
    struct __CVPixelBufferPool *_field12;
    struct __CVPixelBufferPool *_field13;
    struct _CAImageQueue *_field14;
    id _field15;
    id _field16;
    id _field17;
    id _field18;
};

struct _CAImageQueue;

struct __CVPixelBufferPool;

struct _opaque_pthread_mutex_t {
    long _field1;
    char _field2[40];
};

