/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <PhotoBoothEffects/PBFilter.h>

@class PBCompiledFilter;

@interface PBFilter (PBFilterPrivate)
+ (BOOL)needsDisplayForKey:(id)arg1;
+ (id)defaultValueForKey:(id)arg1;
- (void)renderWithContext:(id)arg1 inputSize:(struct CGSize)arg2 outputRect:(struct CGRect)arg3 mirrored:(BOOL)arg4;
- (id)_lookupTableForName:(id)arg1;
- (id)_lookupTableNames;
- (id)_glesUniforms;
- (id)_glesAttributes;
- (const char *)_fragmentShaderSource;
- (const char *)_vertexShaderSource;
@property(retain, nonatomic) PBCompiledFilter *compiledFilter; // @dynamic compiledFilter;
- (id)_presentationName;
- (BOOL)allowAbsoluteGestures;
@end

