/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface PBFilter : NSObject
{
    void *_priv;
}

+ (id)filterWithName:(id)arg1;
- (void)renderQuadInStrips:(int)arg1;
- (void)renderQuadWithOutputSize:(struct CGSize)arg1;
- (id)description;
- (id)localizedName;
- (id)inputKeys;
- (void)setDefaults;
- (void)dealloc;
- (id)name;
- (id)init;

@end

