/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import <PhotoBoothEffects/PBContext.h>

@class PBRuntimeWrapper;

@interface PBOpenCLContext : PBContext
{
    PBRuntimeWrapper *rtWrapper;
}

- (void)applyFilter:(id)arg1 toSurface:(struct __IOSurface *)arg2 mirrored:(BOOL)arg3 surfaceResultHandler:(id)arg4;
- (void)dealloc;
- (id)init;

@end

