/*
 *     Generated by class-dump 3.3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2011 by Steve Nygard.
 */

#import "NSObject.h"

@interface MSBatteryPowerMonitor : NSObject
{
    struct __CFRunLoopSource *_batteryRunLoopSource;
    struct IONotificationPort *_batteryIONotifyPort;
    unsigned int _batteryNotificationRef;
    double _currentLevel;
}

+ (id)defaultMonitor;
- (double)batteryPercentRemaining;
- (void)_updateBatteryLevelWithBatteryEntry:(unsigned int)arg1;
- (void)dealloc;
- (id)init;

@end

